<section class="accueil">
    
    <article class="accueilContain1">
        <h1>Accueil</h1>
        
        <h3> Bienvenue nouveau compagnon !</h3>
        
        <div>
            
            <picture>
                <source  media="(max-width: 768px)" srcset="public/img/site/dog-4415649_640.jpg">
                <source media="(min-width: 768px) " srcset="public/img/site/dog-4415649_1280.jpg">
                <source media="(min-width: 1024px)" srcset="public/img/site/dog-4415649_1920.jpg">
                <img class="imgAccueil" src="public/img/site/dog-4415649_640.jpg" alt="corgi heureux">
                    
            </picture>
            
            
            <p>Bonjour, si vous etes ici car vous recherchez un espace dédié à l'entraide et à la bienveillance alors vous etes au bon endroit, vous pouvez consulter les articles écrits par nos adherents librement, cela répondra certainement à vos questions. Si cela vous en dis, vous pourez nous rejoindre, et à votre tour transmettres vos connaissances à toute notre communauté afin de les aider également!</p>
        </div>
        
        
    </article>
    
    
    
    
    
    <article class="accueilContain2">
        <div>
            <img class="head1" src="public/img/site/clip-art-5864089_640.png" alt="petit chien qui parle"/>
            <p>Bonjour, je m'appel mirtilles, mon maitre m'a créé un profil quand il a créé son compte utilisateur ! Le site est encore en version beta test mais on peut déjà y faire pas mal de choses, de multiples possibilités sont à venir prochainement, inscrivez vous pour avoir la chance de suivre les prochaines fonctionnalités.</p>
            
        </div>
        
        
        
        
        <div>
            
                <img class="head2" src="public/img/site/clip-art-5864090_640.png" alt="petit chien qui parle"/>
                <p>Et salut moi c'est Steve, mon maitre s'est inscrit sur ce site pour apprendre comment faire du canicross, depuis nous partons courir tous les week-ends, et nous partageons nos conseils à tout le monde pour aider les débutants depuis! La communauté s'agrandit et c'est cool !</p>
           
        </div>
        
        
        
    </article>
    
    
    
    
    <article class="accueilContain3">
        
         <img class="img1" src="public/img/site/cat-3744627_1920.jpg" alt="chatton tigré">
         <img class="img2" src="public/img/site/dog-2817560_1920.jpg" alt="berger allemend">
         <img class="img3" src="public/img/site/dog-3735336_1920.jpg" alt="labrador marron">
         <img class="img4" src="public/img/site/dog-4415649_1920.jpg" alt="corgi sur chemin de fer">
         <img class="img5" src="public/img/site/dog-4661341_1920.jpg" alt="cocker marron">
         <img class="img6" src="public/img/site/russian-blue-cat-5774414_1920.jpg" alt="chat gris">
         
        
        
    </article>
    
    
    <article class="accueilContain4">
        
        <div class="corgiSong">
            <iframe  src="https://www.youtube.com/embed/4XsItQX0kgI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        
        
    </article>
    
    
    
    
    
    
</section>


