<section>
    <h1> Notre histoire </h1>
    
    <article class="articleMotivation">
        
        <div>
            <picture>
                <source  media="(max-width: 768px)" srcset="public/img/site/pexels-nataliya-vaitkevich-4445619 (2).jpg">
                <source media="(min-width: 768px) " srcset="public/img/site/pexels-nataliya-vaitkevich-4445619 (1).jpg">
                <source media="(min-width: 1024px)" srcset="public/img/site/pexels-nataliya-vaitkevich-4445619.jpg">
                <img class="imgMotivation" src="public/img/site/pexels-nataliya-vaitkevich-4445619 (2).jpg" alt="corgi penseur">
            </picture>
        </div> 
        
        
        <div>
            <p>je me souviens encore comme si c'etais hier, les jours où je me posais plein de questions, " Comment faire ceci? Comment faire cela? "</p>
            
            <p>je me souviens que j'essayais toujours plein de choses toujours plus differentes les unes que les autres sans jamais n'avoir de resultat très concluant !</p>
            
            <p>Je me souviens avoir pensé, pourquoi n'y a t'il pas plus d'entraide envers  les animaux ? </p>
            
            <p>Toutes cette reflexion nous a ammené à réfléchir, imaginer et concevoir une proposition qui pourra aider un maximum de propriétaire d'animaux, pour trouver des solutions diverses, car comme nous le disons, "seul on va vite !  ensemble nous irons plus loin !</p>
            
            <p>Et comme un grand Homme disais : </p>
            
            <div class="citation">
                <blockquote><i>&laquo; La folie, c'est de faire toujours la même chose et de s'attendre à un résultat différent ! &raquo;</i></blockquote>
                
                <p>Albert EINSTEIN</p>
            </div>
        </div>
        
    </article>
</section>