<thead>
    <tr>
        <th>Utilisateurs</th>
        <th>Animaux</th>
        <th>Commentaires</th>
    </tr>
</thead>

<tbody>
    <?php foreach($users as $user) : ?> 
    
        <tr>
            <td>
                <p>Nom : <?= $user['userInfos']['lastname'] ?></p>
                <p>Prenom : <?= $user['userInfos']['firstname'] ?></p>
                <p>E-mail : <?= $user['userInfos']['mail'] ?></p>
                
                <a href="index.php?route=deleteUserByAdmin&id=<?= $user['userInfos']['id_users']; ?>" name="supprimer_mon_compte" class="btn-red" id="supUser" title="supprimer" >Supprimer</a>
            </td>
            
            
            <td>
                <?php foreach($user['userAnimals'] as $animal) : ?>
                
                    <div id="card" class="card">
                        <img src="<?= $animal['photo'] ?>" class="photoProfilCards" />
                    
                        <div class="infoAnimalShort">
                            <p>Nom : <?= $animal['name'] ?> </p>
                            <a class="btn" href="index.php?route=animalPage&id=<?= $animal['id_animals'] ?>" title="+ d'infos">Voir plus</a>
                        </div>
                        
                    </div>
                    
                <?php endforeach ; ?>
            </td>
            
            
            <td>
                <div>
            
                    <?php foreach($user['userArticles'] as $article ) : ?>
                    
                        <div id="articles" class="articles">
                
                            <h3 class="title"> <?= $article['title']; ?> </h3>
                            
                            <div class="">
                                
                                <h4 class="infoRubrique"> <?= $article['info_rubrique'] ; ?> </h4>
                                <a href="index.php?route=articlePage&id=<?= $article['id_articles']; ?>" class="btn lien" title="+ d'infos" >Voir plus</a>
                            </div>
                        </div>
                    
                    <?php endforeach ; ?>
                </div>
            </td>
            
            
        </tr>
    
    <?php endforeach; ?>
</tbody>