<section>
    <h1> Nos Motivations </h1>
    
    <article class="articleMotivation">
        <div>
            <picture>
                <source  media="(max-width: 768px)" srcset="public/img/site/pexels-nataliya-vaitkevich-5122188 (1).jpg">
                <source media="(min-width: 768px) " srcset="public/img/site/pexels-nataliya-vaitkevich-5122188 (2).jpg">
                <source media="(min-width: 1024px)" srcset="public/img/site/pexels-nataliya-vaitkevich-5122188.jpg">
                <img class="imgMotivation" src="public/img/site/pexels-nataliya-vaitkevich-5122188 (1).jpg" alt="corgi qui travail">
            </picture>
        </div> 
        
        
        <div>
            <p>Nous sommes fiers de pouvoir apporter notre aide à chacun d'entre vous !</p>
            
            <p>Ce qui nous donnes l'envie de continuer chaque jours est de savoir que sur cette espace, vous trouverez tous types de reponse à vos questions !</p>
            
            <p>C'est pourquoi, nous donnons libre accès et gratuitement à tous nos services à chacune et chacun qui souhaitent progresser et s'ameliorer dans l'apprentissage des êtres vivant qui nous accompagne.</p>
            
            <p>Nous vous souhaitons une agréable experience que pourra vous apporter cette plateforme collaborative !</p>
        </div>
    </article>
</section>