<section class="notFound">
    
    <div>
        <img src="public/img/site/kisspng-carnivora-character-clip-art-corgi-5b49040339cbe1.6691467615315118112367.png" class="corgi404"></img>
    </div>
    
    
    <div>
        <p class="text404">Il s'emblerait que vous vous soyez perdu dans la zone 404 !</p>
        <a href="index.php?route=accueil" class="btn">Revenez en lieu sûre !</a>
    </div>
    
</section>